apps/account/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^register/$', views.register, name='register'),
    url(r'^sign_out/$', views.sign_out, name='sign_out'),
]

apps/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

apps/product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.ProductListView.as_view(), name='list'),
    url(
        r'^(?P<slug>[\w-]+)$',
        views.ProductDetailView.as_view(),
        name='detail'
    ),
    url(
        r'^featured/list/$',
        views.ProductFeaturedListView.as_view(),
        name='featured_list'
    ),
    url(
        r'^featured/(?P<slug>[\w-]+)$',
        views.ProductFeaturedDetailView.as_view(),
        name='featured_detail'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^product/', include('apps.product.urls', namespace='product')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/product/models.py
import os

from django.db import models


def get_filename_ext(filepath):
    basename = os.path.basename(filepath)
    return os.path.splitext(basename)


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    new_filename = hash(name)
    return f'products/{instance.pk}/{new_filename}{ext}'


class ProductManager(models.Manager):

    def featured(self, id):
        return self.get_queryset().filter(featured=True)


class Product(models.Model):
    title = models.CharField('title', max_length=120)
    slug = models.SlugField('slug', blank=True, unique=True)
    descripition = models.TextField('descripition')
    price = models.DecimalField(
        'price',
        decimal_places=2,
        max_digits=20,
        default=39.99
    )
    image = models.ImageField(
        'image',
        upload_to=upload_image_path,
        null=True,
        blank=True
    )
    featured = models.BooleanField('featured', default=False)

    objects = ProductManager()

    def __str__(self):
        return self.title

apps/account/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class RegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'Your email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label='Confirm password',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)

        if qs.exists():
            raise forms.ValidationError('Username is taken')

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)

        if qs.exists():
            raise forms.ValidationError('Email is taken')

        return email

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError('Passwords must match.')

        return data

apps/core/forms.py
from django import forms


class ContactForm(forms.Form):
    fullname = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Your full name'}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'Your email'}
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'placeholder': 'Your message'}
        )
    )

apps/account/views.py
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.shortcuts import redirect, render
from django.urls import resolve

from . import forms


def sign_in(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = forms.LoginForm()

    return render(request, 'account/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)

        if form.is_valid():
            User = get_user_model()

            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            User.objects.create_user(username, email, password)

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = forms.RegisterForm()
    return render(request, 'account/register.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('/')

apps/core/views.py
from django.shortcuts import render

from . import forms


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')


def contact(request):
    form = forms.ContactForm(request.POST or None)
    return render(request, 'core/contact.html', {'form': form})

apps/product/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404

from . import models


class ProductListView(generic.ListView):
    queryset = models.Product.objects.all()
    template_name = 'product/list.html'


class ProductFeaturedListView(generic.ListView):
    template_name = 'product/list.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return models.Product.objects.featured()


class ProductDetailView(generic.DetailView):
    queryset = models.Product.objects.all()
    template_name = 'product/detail.html'

    def get_context_data(self, *args, **kwargs):
        return super(ProductDetailView, self).get_context_data(*args, **kwargs)


class ProductFeaturedDetailView(generic.DetailView):
    template_name = 'product/detail.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return models.Product.objects.featured()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>E-Commerce</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'popper.js' %}"></script>
    <script src="{% static 'bootstrap.js' %}"></script>
</body>
</html>

templates/core/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About</h1>
{% endblock content %}

templates/core/contact.html
{% extends 'base.html' %}
{% block content %}
    <h1>Contact</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
{% endblock content %}

templates/core/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Hello, world!</h1>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Django E-Commerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/product/list">Products</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/contact">Contact</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <a class="nav-link" href="#">Welcome {{ user }}</a>
                <a class="nav-link" href="/account/sign_out">Sign Out</a>
            {% else %}
                <a class="nav-link" href="/account/sign_in">Sign In</a>
                <a class="nav-link" href="/account/register">Register</a>
            {% endif %}
        </div>
    </div>
</nav>

templates/product/detail.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <li>{{ product.title }}</li>
        <li>{{ product.descripition }}</li>
        <li>{{ product.price }}</li>
        <li><img src="{{ product.image.url }}" class="img-fluid"/></li>
    </ul>
{% endblock content %}

templates/product/list.html
{% extends 'base.html' %}
{% block content %}
    {% for product in object_list %}
        <ul>
            <li>
                <a href="{% url 'product:detail' product.slug %}">
                    {{ product.title }}
                </a>
            </li>
            <li>{{ product.descripition }}</li>
            <li>{{ product.price }}</li>
        </ul>
    {% endfor%}
{% endblock content %}